# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1545, 779)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.field = QtWidgets.QLabel(self.centralwidget)
        self.field.setGeometry(QtCore.QRect(960, 140, 512, 341))
        self.field.setText("")
        self.field.setPixmap(QtGui.QPixmap("assets/halisaha.png"))
        self.field.setScaledContents(True)
        self.field.setObjectName("field")
        self.start = QtWidgets.QPushButton(self.centralwidget)
        self.start.setGeometry(QtCore.QRect(960, 500, 511, 41))
        self.start.setObjectName("start")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 10, 911, 601))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.videoLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.videoLayout.setContentsMargins(0, 0, 0, 0)
        self.videoLayout.setObjectName("videoLayout")
        self.load = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.load.setObjectName("load")
        self.videoLayout.addWidget(self.load)
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 650, 921, 51))
        self.layoutWidget.setObjectName("layoutWidget")
        self.mediaBar = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.mediaBar.setContentsMargins(0, 0, 0, 0)
        self.mediaBar.setObjectName("mediaBar")
        self.play = QtWidgets.QPushButton(self.layoutWidget)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("assets/play_arrow-24px.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.play.setIcon(icon)
        self.play.setObjectName("play")
        self.mediaBar.addWidget(self.play)
        self.pause = QtWidgets.QPushButton(self.layoutWidget)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("assets/pause-24px.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pause.setIcon(icon1)
        self.pause.setObjectName("pause")
        self.mediaBar.addWidget(self.pause)
        self.motion = QtWidgets.QLabel(self.centralwidget)
        self.motion.setGeometry(QtCore.QRect(960, 140, 512, 341))
        self.motion.setAutoFillBackground(False)
        self.motion.setText("")
        self.motion.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.motion.setObjectName("motion")
        self.layoutWidget.raise_()
        self.field.raise_()
        self.start.raise_()
        self.verticalLayoutWidget.raise_()
        self.motion.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1545, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.start.setText(_translate("MainWindow", "Start Tracking"))
        self.load.setText(_translate("MainWindow", "Load"))
        self.play.setText(_translate("MainWindow", "Play"))
        self.pause.setText(_translate("MainWindow", "Pause"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
